import React, { useEffect, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, Crosshair, Maximize2, ShieldCheck, X } from 'lucide-react';
import { useLanguage } from '../i18n/LanguageContext';

interface InfrastructureNetworksPageProps { onNavigate: (pageId: string) => void; }
type Evidence = { file: string; ar: string; en: string; fit?: boolean };
const path = (file: string) => `/images/infrastructure-network/${encodeURIComponent(file)}`;
const shot = (n: string, ar: string): Evidence => ({ file: `Screenshot 2026-09-29 ${n}.png`, ar, en: 'Operational map and layer view', fit: true });

const stages = [
  { no:'01', tag:['تثبيت مرجع الموقع','Locate & control'], title:['نبدأ من الموقع لا من التخمين','Start at the site, not an assumption'], text:['يربط فريق الرفع نقاط الرصد بمعالم الموقع الفعلية، ثم يُراجع مواقع العناصر قبل إدخالها إلى الطبقات المكانية.','The survey team ties control points to real site features before assets enter the spatial record.'], primary:{file:'01-gnss-field-survey.png',ar:'فريق مساحي يستخدم جهاز GNSS في موقع مفتوح',en:'Survey team using GNSS equipment on site'}, evidence:[{file:'21-gnss-network-survey.png',ar:'تثبيت نقاط رفع على مسار الشبكة',en:'Network alignment control survey'},{file:'31-gnss-network-survey-team.jpg',ar:'فريق مسح يعمل بجهاز رصد ميداني',en:'GNSS survey team at work'},{file:'35-gnss-site-survey.jpg',ar:'رفع موقع بجهاز GNSS ثلاثي القوائم',en:'Tripod GNSS site survey'},shot('134604','واجهة خريطة لمسار خط مرصود مع قائمة طبقات')] },
  { no:'02', tag:['توثيق الأصل','Record the asset'], title:['كل غرفة ومحبس له سجل مكاني','Every chamber and valve gets a spatial record'], text:['توثيق المحابس وغرف التفتيش بالصور والموقع يحوّل الملاحظة الميدانية إلى أصل يمكن لفريق التشغيل الرجوع إليه.','Photographs and positions turn field observations into operational assets the team can retrieve.'], primary:{file:'02-water-valve-field-inspection.png',ar:'مواسير ومحبس مياه داخل غرفة تفتيش',en:'Water pipes and valve inside an inspection chamber'}, evidence:[{file:'15-water-valve-and-irrigation-assets.png',ar:'عناصر محابس مياه وري ظاهرة بالموقع',en:'Water and irrigation valve assets'},{file:'32-water-valve-chamber-inspection.jpg',ar:'معاينة غرفة محبس مياه',en:'Water valve chamber inspection'},{file:'04-wastewater-manhole-inspection.png',ar:'فحص غرفة تفتيش للصرف الصحي',en:'Wastewater manhole inspection'},shot('134712','لوحة خريطة بأعمدة إحصائية وعناصر ملوّنة')] },
  { no:'03', tag:['كشف ما تحت السطح','Detect below grade'], title:['نقرأ المرافق الخفية قبل التعارض','Read hidden utilities before conflict'], text:['تُطابق نتائج المسح الراداري ومعاينات الصرف مع المشاهدات الميدانية لتقليل المفاجآت أسفل مسار العمل.','Radar results and wastewater observations are checked against site evidence to reduce below-grade surprises.'], primary:{file:'03-gpr-underground-utility-scan.png',ar:'تشغيل جهاز رادار أرضي لكشف مرفق مدفون',en:'Ground-penetrating radar survey for buried utility'}, evidence:[{file:'14-gpr-utilities-detection.jpeg',ar:'مسح راداري أرضي على سطح الموقع',en:'Ground radar utility detection'},{file:'22-sewer-inspection-terrain.png',ar:'مسار فحص صرف صحي في تضاريس موقع',en:'Sewer inspection along site terrain'},{file:'28-wastewater-manhole-inspection.jpg',ar:'فتحة تفتيش صرف صحي أثناء المعاينة',en:'Wastewater manhole under inspection'},shot('134939','خريطة شبكة ملوّنة مع جدول خصائص جانبي')] },
  { no:'04', tag:['ربط الطبقات','Link the layers'], title:['نحوّل الأدلة إلى خريطة قرار واحدة','Turn evidence into one decision map'], text:['تُربط طبقات المرافق والمخططات الهندسية وسياق القطع على خريطة واحدة لقراءة المسارات ونقاط التداخل بوضوح.','Utility layers, engineering plans, and parcel context are linked on one map to make routes and overlaps clear.'], primary:{file:'07-utility-network-gis-map.png',ar:'خريطة GIS لمسارات مرافق وعناصر شبكة',en:'GIS utility map with network routes and assets',fit:true}, evidence:[{file:'09-land-parcel-utility-conflict-context.jpg',ar:'سياق قطع أراضٍ مقابل مسارات مرافق',en:'Land parcels in utility-conflict context',fit:true},{file:'10-utility-conflict-engineering-plan.png',ar:'مخطط هندسي يوضح معالجة تعارض مرافق',en:'Engineering plan for a utility conflict',fit:true},{file:'19-utility-conflict-study-plan.png',ar:'لوحة دراسة لمسارات وتعارضات المرافق',en:'Utility conflict study plan',fit:true},shot('135051','خريطة مقارنة لمنطقتين ملوّنتين ضمن لوحة قرار')] },
  { no:'05', tag:['قرار الجاهزية','Decide readiness'], title:['نراجع الحالة قبل أن نتحرك','Review readiness before action'], text:['تجمع اللوحات حالة الأصول والطبقات ومسارات التنفيذ في قراءة تشغيلية واحدة تساعد على ترتيب الأولويات ومراجعة الجاهزية.','Operational screens combine asset status, layers, and delivery paths to prioritize work and review readiness.'], primary:{file:'20-technical-readiness-report.png',ar:'تقرير جاهزية فني يعرض مؤشرات وخرائط',en:'Technical readiness report with maps and indicators',fit:true}, evidence:[{file:'24-infrastructure-network-map-dashboard-illustrative.png',ar:'لوحة خريطة لشبكات البنية التحتية',en:'Infrastructure network map dashboard',fit:true},{file:'25-asset-verification-dashboard-illustrative.png',ar:'لوحة تحقق من عناصر الأصول وحالتها',en:'Asset verification status dashboard',fit:true},{file:'26-land-and-utility-conflict-dashboard-illustrative.png',ar:'لوحة تعارضات بين الأرض ومسارات المرافق',en:'Land and utility conflict dashboard',fit:true},shot('135132','لوحة زمنية لمراحل التنفيذ مع خريطة نطاق العمل')] },
];

const indexEvidence: Evidence[] = [
  ['05-quality-control-field-inspection.png','تحقق جودة ميداني','Field quality check'],['06-electrical-network-documentation.png','توثيق عنصر شبكة كهربائية','Electrical asset documentation'],['13-water-station-and-reservoirs.png','محطة مياه وخزانات','Water station and reservoirs'],['16-mobile-gis-data-collection.png','جمع بيانات عبر GIS متنقل','Mobile GIS data collection'],['23-qaqc-site-review.png','مراجعة جودة بالموقع','On-site quality review'],['27-field-utility-verification-team.jpg','فريق تحقق من مرافق الموقع','Field utility verification team'],['29-gas-network-map-dashboard.jpg','لوحة خريطة لشبكة الغاز','Gas network map dashboard'],['30-wastewater-asset-field-check.jpg','تحقق ميداني من أصل صرف صحي','Wastewater asset field check'],['33-field-mapping-and-asset-review.jpg','مراجعة طبقات الأصول ميدانياً','Field mapping and asset review'],['34-infrastructure-asset-coordination.jpg','تنسيق عناصر البنية التحتية','Infrastructure asset coordination'],['11-urban-utility-network-masterplan.png','مخطط عام لشبكات المرافق الحضرية','Urban utility network masterplan']
].map(([file, ar, en]) => ({file, ar, en, fit: file.includes('png')}));
const dashboardLabels = ['خريطة نطاق خدمات وطبقات تشغيلية','لوحة مراجعة طبقات وعناصر','خريطة قطع وممرات مرافق','خريطة تشغيلية مع جدول عناصر','طبقات شبكة ملوّنة ضمن لوحة متابعة','خريطة أصل محدد مع بياناته','مقارنة طبقات شبكات ملوّنة','خريطة حالة شبكة ضمن نطاق حضري','لوحة متابعة أصول ومؤشرات','خريطة قرار لمسار خدمة','خريطة عناصر عالية الأولوية','لوحة حالة تشغيلية وطبقات'];
['134629','134757','134828','134839','134904','134914','134946','134953','135010','135018','135033','135114'].forEach((time, i) => indexEvidence.push(shot(time, dashboardLabels[i])));

export const InfrastructureNetworksPage: React.FC<InfrastructureNetworksPageProps> = ({ onNavigate }) => {
  const { isAr } = useLanguage(); const [selected, setSelected] = useState<Evidence | null>(null);
  const tr = (a:string,b:string) => isAr ? a : b; const all = [...stages.flatMap(s => [s.primary,...s.evidence]),...indexEvidence]; const current = selected ? all.findIndex(x => x.file === selected.file) : 0;
  useEffect(() => { const f=(e:KeyboardEvent)=>e.key==='Escape'&&setSelected(null); window.addEventListener('keydown',f); return()=>window.removeEventListener('keydown',f); },[]);
  const Image = ({item,className=''}:{item:Evidence;className?:string}) => <button type="button" onClick={()=>setSelected(item)} className={`group relative block overflow-hidden bg-[#06182c] text-start focus:outline-none focus:ring-2 focus:ring-cyan-300 ${className}`}><img src={path(item.file)} alt={tr(item.ar,item.en)} loading="lazy" className={`h-full w-full ${item.fit?'object-contain':'object-cover'} transition duration-500 group-hover:scale-[1.025]`}/><span className="absolute top-3 end-3 grid h-8 w-8 place-items-center bg-slate-950/75 text-white opacity-0 transition group-hover:opacity-100"><Maximize2 size={15}/></span></button>;
  return <main dir={isAr?'rtl':'ltr'} className="overflow-hidden bg-[#f5f9fb] font-['Cairo',sans-serif] text-slate-800">
    <header className="relative overflow-hidden border-b border-cyan-200 bg-[#06182c] text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(34,211,238,.35)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,.35)_1px,transparent_1px)] [background-size:34px_34px]"/><div className="relative mx-auto max-w-7xl px-5 py-16 md:py-20"><p className="mb-4 flex items-center gap-2 text-xs font-bold tracking-[.16em] text-cyan-300"><Crosshair size={16}/>{tr('دورة تشغيل شبكات البنية التحتية','INFRASTRUCTURE OPERATING LOOP')}</p><h1 className="max-w-4xl text-3xl font-black leading-tight md:text-5xl">{tr('من الرصد الميداني إلى قرار جاهزية يمكن تتبّعه','From field observation to traceable readiness')}</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-slate-300 md:text-base">{tr('خمس محطات مترابطة: نثبت الموقع، نوثق الأصل، نكشف ما تحت السطح، نربط الطبقات، ثم نراجع قرار التنفيذ.','Five linked stations: locate, document, detect, connect layers, then review delivery readiness.')}</p><div className="mt-9 grid max-w-4xl grid-cols-5 border border-cyan-300/30">{stages.map(s=><div key={s.no} className="border-s border-cyan-300/25 px-3 py-3 first:border-0"><b className="block text-cyan-300">{s.no}</b><span className="mt-1 hidden text-xs leading-5 text-slate-300 sm:block">{tr(s.tag[0],s.tag[1])}</span></div>)}</div></div></header>
    {stages.map((s,i)=><section key={s.no} className={`${i%2?'bg-[#071a2f] text-white':'bg-white'} relative py-14 md:py-20`}><div className="absolute inset-x-0 top-0 h-px bg-cyan-300/40"/><div className="mx-auto max-w-7xl px-5"><div className="grid items-center gap-8 lg:grid-cols-12 lg:gap-12"><article className={`lg:col-span-5 ${i%2?'lg:order-2':''}`}><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center border border-cyan-400/50 font-black text-cyan-400">{s.no}</span><p className="text-xs font-bold tracking-[.13em] text-cyan-500">{tr(s.tag[0],s.tag[1])}</p></div><h2 className="text-3xl font-black leading-tight md:text-4xl">{tr(s.title[0],s.title[1])}</h2><p className={`mt-5 max-w-xl text-sm leading-8 md:text-base ${i%2?'text-slate-300':'text-slate-600'}`}>{tr(s.text[0],s.text[1])}</p><div className={`mt-7 flex items-center gap-3 border-s-2 border-cyan-400 ps-4 text-sm ${i%2?'text-slate-200':'text-slate-700'}`}><ShieldCheck className="shrink-0 text-cyan-500" size={20}/><span>{tr('دليل ميداني ومكاني مرتبط بسياق القرار.','Field and spatial evidence linked to its decision context.')}</span></div></article><div className={`lg:col-span-7 ${i%2?'lg:order-1':''}`}><div className="grid gap-3 sm:grid-cols-12"><div className="sm:col-span-8"><Image item={s.primary} className="h-[280px] border border-cyan-300/30 sm:h-[420px]"/><p className={`mt-2 text-xs ${i%2?'text-slate-400':'text-slate-500'}`}>{tr(s.primary.ar,s.primary.en)}</p></div><aside className="grid grid-cols-2 gap-3 sm:col-span-4 sm:grid-cols-1" aria-label={tr('أدلة مساندة','Supporting evidence')}>{s.evidence.map((e,n)=><div key={e.file}><Image item={e} className="h-28 border border-cyan-300/25 sm:h-[94px]"/><p className={`mt-1 line-clamp-2 text-[11px] leading-5 ${i%2?'text-slate-300':'text-slate-600'}`}><span className="me-1 text-cyan-500">0{n+1}</span>{tr(e.ar,e.en)}</p></div>)}</aside></div></div></div></div></section>)}
    <section className="border-t border-cyan-200 bg-[#eef6f8] py-14"><div className="mx-auto max-w-7xl px-5"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold tracking-[.14em] text-cyan-700">{tr('فهرس الأدلة المرتبطة','LINKED EVIDENCE INDEX')}</p><h2 className="mt-2 text-2xl font-black text-[#092540]">{tr('سجل إضافي للمعاينة — حسب السياق لا كمعرض صور','Additional inspection record — by context, not a gallery')}</h2></div><p className="max-w-md text-sm leading-7 text-slate-600">{tr('افتح أي سجل لمراجعته بالحجم الكامل؛ جميع الأدلة مرتبطة بمحطة من دورة العمل أعلاه.','Open any record for full inspection; every item belongs to an operating stage above.')}</p></div><div className="mt-8 grid gap-px border border-cyan-200 bg-cyan-200 sm:grid-cols-2 lg:grid-cols-3">{indexEvidence.map((e,n)=><button key={e.file} onClick={()=>setSelected(e)} className="group flex min-h-16 items-center gap-3 bg-white px-4 py-3 text-start hover:bg-cyan-50 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-cyan-500"><span className="font-mono text-xs text-cyan-700">{String(n+21).padStart(2,'0')}</span><span className="flex-1 text-xs font-bold leading-5 text-slate-700">{tr(e.ar,e.en)}</span><ArrowLeft size={16} className="text-cyan-700 transition group-hover:-translate-x-1"/></button>)}</div><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>onNavigate('contact')} className="bg-[#092540] px-6 py-3 text-sm font-bold text-white hover:bg-[#0d365c]">{tr('ابدأ مراجعة شبكة موقعك','Start your network review')}</button><button onClick={()=>onNavigate('methodology')} className="border border-[#092540] px-6 py-3 text-sm font-bold text-[#092540] hover:bg-white">{tr('استعرض منهجية العمل','View methodology')}</button></div></div></section>
    {selected&&<div className="fixed inset-0 z-[80] flex flex-col bg-[#020b15]/95 p-4 text-white backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={tr(selected.ar,selected.en)}><div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4 border-b border-white/15 pb-3"><div><p className="text-xs font-bold text-cyan-300">{tr('دليل من سياق التشغيل','OPERATING CONTEXT EVIDENCE')}</p><h3 className="mt-1 text-base font-bold">{tr(selected.ar,selected.en)}</h3></div><button onClick={()=>setSelected(null)} className="p-2 text-white hover:bg-white/10" aria-label={tr('إغلاق','Close')}><X/></button></div><div className="relative mx-auto flex min-h-0 w-full max-w-6xl flex-1 items-center justify-center py-5"><img src={path(selected.file)} alt={tr(selected.ar,selected.en)} className="max-h-full max-w-full object-contain"/><button onClick={()=>setSelected(all[(current-1+all.length)%all.length])} className="absolute start-0 bg-slate-900/80 p-3 hover:bg-cyan-700" aria-label={tr('الدليل السابق','Previous evidence')}>{isAr?<ChevronRight/>:<ChevronLeft/>}</button><button onClick={()=>setSelected(all[(current+1)%all.length])} className="absolute end-0 bg-slate-900/80 p-3 hover:bg-cyan-700" aria-label={tr('الدليل التالي','Next evidence')}>{isAr?<ChevronLeft/>:<ChevronRight/>}</button></div></div>}
  </main>;
};
